In [1]:
# 경고 무시
import warnings
warnings.filterwarnings(action='ignore')

In [2]:
import pandas as pd
import numpy as np
import random
import tensorflow as tf

In [3]:
# 랜덤 시드 고정
# SEED = 12
# random.seed(SEED)
# np.random.seed(SEED)
# tf.random.set_seed(SEED)
# print('시드는.. ', SEED)
# 시드는..  12

In [4]:
# sklearn 데이터셋에서 보스턴 주택 데이터셋 로딩
from sklearn import datasets

In [5]:
boston = datasets.load_boston()
X_data = boston.data

In [6]:
y_data = boston.target

In [7]:
print(X_data.shape, y_data.shape)

(506, 13) (506,)


In [8]:
y_data[:3]

array([24. , 21.6, 34.7])

In [9]:
X_data[0]

array([6.320e-03, 1.800e+01, 2.310e+00, 0.000e+00, 5.380e-01, 6.575e+00,
       6.520e+01, 4.090e+00, 1.000e+00, 2.960e+02, 1.530e+01, 3.969e+02,
       4.980e+00])

In [10]:
boston.keys()

dict_keys(['data', 'target', 'feature_names', 'DESCR', 'filename', 'data_module'])

In [11]:
boston.feature_names

array(['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD',
       'TAX', 'PTRATIO', 'B', 'LSTAT'], dtype='<U7')

In [12]:
## 전처리
from sklearn.preprocessing import MinMaxScaler

In [13]:
min_max = MinMaxScaler()
x_data_min_max = min_max.fit_transform(X_data)
x_data_min_max[0]

array([0.        , 0.18      , 0.06781525, 0.        , 0.31481481,
       0.57750527, 0.64160659, 0.26920314, 0.        , 0.20801527,
       0.28723404, 1.        , 0.08967991])

In [14]:
from keras.models import Sequential
from tensorflow.keras.layers import Dense
## 딥러닝 모델 만들어서
model = Sequential()
# Dense에 값을 넣지 않으면 default 값으로 들어간다
model.add(Dense(128, activation='relu', input_dim=13))
model.add(Dense(64, activation='relu'))
model.add(Dense(1, activation='linear')) # 회귀이므로 linear

In [15]:
## 위에 쌓은 모델로 설정
# mae: 오차 간의 절댓값
model.compile(optimizer='adam', loss='mse', metrics=['mae'])
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 128)               1792      
                                                                 
 dense_1 (Dense)             (None, 64)                8256      
                                                                 
 dense_2 (Dense)             (None, 1)                 65        
                                                                 
Total params: 10,113
Trainable params: 10,113
Non-trainable params: 0
_________________________________________________________________


In [20]:
## 공부시키고
model.fit(x_data_min_max[:400], y_data[:400], epochs=3, batch_size=50, verbose=2)

Epoch 1/3
8/8 - 0s - loss: 90.9449 - mae: 7.0639 - 9ms/epoch - 1ms/step
Epoch 2/3
8/8 - 0s - loss: 85.3028 - mae: 6.8475 - 6ms/epoch - 730us/step
Epoch 3/3
8/8 - 0s - loss: 80.2286 - mae: 6.6511 - 9ms/epoch - 1ms/step


In [21]:
## 정확도 계산
model.evaluate(x_data_min_max[400:], y_data[400:])

4/4 [==============================] - 0s 2ms/step - loss: 92.0529 - mae: 8.4128


[92.05294036865234, 8.412819862365723]